#!/bin/bash -p

daemon="/Library/LaunchDaemons/com.42tools.lorica.plist"
storage="/private/var/db/lorica"

# Create the directory where Lorica stores persisten files
mkdir -p $storage

# PackageMaker changes the premission of the launch file..
chmod 644 $daemon

# Restart Lorica
sudo launchctl unload $daemon
sudo launchctl load $daemon
