#!/bin/bash
# Creates a disk image contaning Lorica and osx support tools.

export APP_NAME="Lorica"
export BUILD="$(pwd)/$APP_NAME.build"
export DIST="$BUILD/dist"

# Delete old build files
chmod -R u+w $BUILD
rm -rf $BUILD

# Create project folders
mkdir -p $BUILD
mkdir -p $DIST

# Stage install
ROOT="$BUILD/root"
mkdir -p $ROOT

pushd ..
if !(./bootstrap --enable-tao-build --enable-lorica-devel --enable-lorica-target=darwin --prefix="/usr" --sysconfdir="/private/etc"); then
    echo "Could not bootstrap Lorica installation"
    exit 1
fi

if !(make && make DESTDIR=$ROOT install); then
    echo "Could not stage installation of Lorica"
    exit 1
fi
popd

# Create installer package
export ROOT

pushd installer
if !(./build); then
    echo "Could not create installer package"
    exit 1
fi
popd

# Create uninstaller applicaion
pushd uninstaller
if !(./build); then
    echo "Could not create uninstaller application"
    exit 1
fi
popd

# Create disk image
pushd diskimage
if !(./build); then
    echo "Could not create disk image"
    exit 1
fi
popd
