// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:487

#ifndef _TAO_IDL_TESTS_H_
#define _TAO_IDL_TESTS_H_


#include "testC.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/Collocation_Proxy_Broker.h"
#include "tao/PortableServer/PortableServer.h"
#include "tao/PortableServer/Servant_Base.h"

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_sh.cpp:87

class POA_Simple_Server;
typedef POA_Simple_Server *POA_Simple_Server_ptr;

class  POA_Simple_Server
  : public virtual PortableServer::ServantBase
{
protected:
  POA_Simple_Server (void);

public:
  // Useful for template programming.
  typedef ::Simple_Server _stub_type;
  typedef ::Simple_Server_ptr _stub_ptr_type;
  typedef ::Simple_Server_var _stub_var_type;
  
  POA_Simple_Server (const POA_Simple_Server& rhs);
  virtual ~POA_Simple_Server (void);
  
  virtual ::CORBA::Boolean _is_a (const char* logical_type_id);
  
  static void _is_a_skel (
      TAO_ServerRequest & req,
      void * servant_upcall,
      void * servant
    );
  
  static void _non_existent_skel (
      TAO_ServerRequest & req,
      void * servant_upcall,
      void * servant
    );
  
  static void _interface_skel (
      TAO_ServerRequest & req,
      void * servant_upcall,
      void * servant
    );
  
  static void _component_skel (
      TAO_ServerRequest & req,
      void * servant_upcall,
      void * servant
    );
  
  static void _repository_id_skel (
      TAO_ServerRequest & req,
      void * servant_upcall,
      void * servant);
  
  virtual void _dispatch (
      TAO_ServerRequest & req,
      void * servant_upcall);
  
  ::Simple_Server *_this (void);
  
  virtual const char* _interface_repository_id (void) const;
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_sh.cpp:45
  
  virtual ::CORBA::Short s (
      void) = 0;
  
  static void _get_s_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_sh.cpp:45
  
  virtual void s (
      ::CORBA::Short s) = 0;
  
  static void _set_s_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_sh.cpp:45
  
  virtual ::CORBA::Boolean any_test (
      const ::CORBA::Any & a) = 0;
  
  static void any_test_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_sh.cpp:45
  
  virtual ::CORBA::Long struct_test (
      ::CORBA::Long x,
      const ::Structure & the_in_structure,
      ::Structure_out the_out_structure,
      char *& name) = 0;
  
  static void struct_test_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_sh.cpp:45
  
  virtual void give_union (
      const ::Test_Union & arg) = 0;
  
  static void give_union_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_sh.cpp:45
  
  virtual ::CORBA::Object_ptr echo_object (
      ::CORBA::Object_ptr obj) = 0;
  
  static void echo_object_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_sh.cpp:45
  
  virtual void raise_user_exception (
      void) = 0;
  
  static void raise_user_exception_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_sh.cpp:45
  
  virtual void raise_system_exception (
      void) = 0;
  
  static void raise_system_exception_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
  
  // TAO_IDL - Generated from
  // be/be_visitor_operation/operation_sh.cpp:45
  
  virtual void shutdown (
      void) = 0;
  
  static void shutdown_skel (
      TAO_ServerRequest & server_request,
      void * servant_upcall,
      void * servant
    );
};

// TAO_IDL - Generated from 
// be/be_codegen.cpp:1288


#if defined (__ACE_INLINE__)
#include "testS.inl"
#endif /* defined INLINE */

#endif /* ifndef */

