#!/bin/bash

#  Creates a disk image contaning the files in $DIST and add a SLA which
#  is shown before osx mounts the image.
#
#  Copyright (C) 2008 OMC Denmark ApS
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
#  MA 02111-1307 USA

# Add background picture
IMAGE_DIR=$DIST/.background
mkdir $IMAGE_DIR
cp image.png $IMAGE_DIR

# Add handcrafted DS_Store file
cp DS_Store $DIST/.DS_Store

# Hide the installer package extension in finder
osascript -e "tell application \"Finder\"" \
          -e    "set extension hidden of file (POSIX file \"$DIST/Install $APP_NAME.pkg\") to true" \
          -e "end tell"

# Create disk image
hdiutil create -srcfolder $DIST -format UDBZ -volname "$APP_NAME Install Disk" -mode 444 -noscrub $BUILD/$APP_NAME.dmg

# Add SLA to disk image
hdiutil unflatten $BUILD/$APP_NAME.dmg
ditto -x SLA.bz2 $BUILD
DeRez $BUILD/sla.rsrc > $BUILD/sla.r
Rez -a $BUILD/sla.r -o $BUILD/$APP_NAME.dmg
hdiutil flatten $BUILD/$APP_NAME.dmg
